include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - avoid_dynamic_calls

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
